spring:
  application:
    name: sales-service
  datasource:
    url: jdbc:mysql://localhost:3306/sales
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
  openfeign:
    enabled: true  # Enable Feign Client
