FROM eclipse-temurin:21-jdk-focal

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Installing dependencies
RUN ./mvnw dependency:go-offline

COPY src ./src

# Build and run the application
CMD ["./mvnw", "spring-boot:run"]
